- src/actions/index.js
- src/api/index.js
- src/components/Group.js
- src/pages/SettingsPage.js
- src/reactors/index.js
There are some small things like fixing a broken dashboard group view link, adding a Questrade authorize button to the Settings page, and adding a missing Content-Type header to the getPost function. Slightly larger is getting the app to pull account settings data from the API.
> A hodgepodge of small things I've been playing with.

- src/actions/index.js
- src/components/Group.js
- src/reducers/index.js
- src/selectors/index.js
Added basic support for the group info endpoint, using it as the default source for group data.
> Playground

- src/components/Accounts/AccountRow.tsx
- src/components/Accounts/styles.ts
- src/components/CreditCardDetails.tsx
- src/components/PortfolioGroupSettings/PreferredCurrencySetting.tsx
- src/components/SlideMenu/MenuButton.tsx
- src/components/SubscriptionManager.tsx
- src/styled/Form.ts
- src/styled/GlobalElements.ts
> Drop down style update

- src/components/CurrencySelector/index.tsx
- src/components/PortfolioGroupTargets/TargetBar/SymbolSelector.tsx
- Dropdown fix for symbol selector on overview page
- Dropdown fix to currency drop down on dashboard
> z-index fixes to dropdown "popups"

- cypress/integration/auth.spec.js
- yarn.lock
Assignment 1: proof of completion 
Assignment 2: 
Completed all the tasks asked on assignment 2. 
The only part that I wasn't able to complete as it was requested is having a token as a response for the successful login. I'm assuming this is because the backend doesn't recognize this enforced response for the POST request and it causes the whole application to fail. 
Some small suggestions: 
* The error messages (email/password is invalid) would be better to be in red.  
* When the button is disabled, it is better to see the button in a different color (Grey) or change the cursor to 'not-allowed'. 
Thanks
> Assignment 1 and 2 

- src/components/Goals/GoalProjectionLineChart.tsx
- src/components/Goals/GoalSetup.tsx
- src/components/Goals/GoalWidget.tsx
- src/components/Goals/Goals.tsx
- src/pages/GoalDetailPage.tsx
1. Plant growing up setup
2. Further mobile Clean up
3. Moved show detail view button moved on to graph
> Goal styling

- src/components/SlideMenu/SideBar.tsx
- src/components/SlideMenu/SideBarLink.tsx
**Did:**
- removed arrows
- less height per item
- green hover 
**To do:**
Accordion for portfolio groups and their accounts
> tweaks to sidebar menu styling - phase 1

- src/components/Performance/Performance.tsx
- src/components/Performance/PerformanceContributionChart.tsx
- src/components/Performance/PerformanceFees.tsx
- src/components/Performance/SettingsComponents/Settings.tsx
- src/types/performance.ts
front end changes for new reporting setting (prefer grouping contributions by month rather than year)
> changes related to new reporting setting (contributions by month)

- src/components/ModelPortfolio/AssetClassSelector.tsx
- src/components/PortfolioGroupTargets/TargetBar/SymbolSelector.tsx
- src/styled/global.tsx
- src/types/groupInfo.ts
> add crypto badge to crypto securities in symbol selector

- src/components/ModelPortfolio/Prioritization/index.tsx
- src/components/NewAssetsDetected.tsx
- src/components/PortfolioGroupSettings/ExcludedAssets.tsx
- src/components/PortfolioGroupSettings/SettingsCheckBox.tsx
- src/selectors/groups.ts
> Exclude multiple assets

- src/components/ModelPortfolio/ModelPortfolioBox.tsx
> Equale weighting

- src/components/PortfolioGroupDetails/PortfolioGroupTotal.tsx
> fix: a bug with seeing a 0 beside total value if total value is 0

- src/components/Tour/TourSteps.tsx
> fix: remove an unneccessary empty tour step

- src/components/PortfolioGroupTargets/TargetBar/SymbolSelector.tsx
> add crypto tag for asset classes

- src/components/ModelPortfolio/MoreOptions.tsx
- src/selectors/groups.ts
- src/types/modelPortfolio.ts
> change how we detect asset classes that need priorities varification and remove (Copy) when duplicate a model

- src/components/PortfolioGroupTargets/index.tsx
- src/pages/MyModelPortfoliosPage.tsx
> Styling changes

- src/components/OverviewTab.tsx
- src/pages/DashboardPage.tsx
- src/pages/MyModelPortfoliosPage.tsx
- src/selectors/groups.ts
----- 
- Fix an issue where the Accuracy shows the spinner if other groups are loading 
- Fix an issue where the chevron button (for listing all the groups using a model) gets triggered for all models
> More bug fixes

- src/selectors/groups.ts
…calculating right for security-based models. 
Airtable record: https://airtable.com/tbldW5ApEcDfH86s7/viw1jn0Qj7F4b8zcY/rec2G4kMGPEvQAIJq?blocks=hide
> fix: issue with actual percentage being 0 for asset classes and not 

- src/components/PortfolioGroupSettings/OrderTargetAllocations.tsx
- src/components/PortfolioGroupTargets/index.tsx
- src/selectors/groups.ts
> fix: add a sorting method for sorting targets alphabetically

- src/components/PortfolioGroupTargets/CashBar.tsx
- src/components/PortfolioGroupTargets/TargetBar/index.tsx
> Add tooltip for portfolio group percentages

- src/components/ModelPortfolio/ModelPortfolioBox.tsx
> Unnecessary group load

- src/components/ModelPortfolio/Prioritization/AssetClassPriority.tsx
- src/components/ModelPortfolio/Prioritization/SecurityPriority.tsx
- src/components/ModelPortfolio/Prioritization/index.tsx
- src/components/PortfolioGroupDetails/PortfolioGroupAccuracy.tsx
- src/components/PortfolioGroupTrades.tsx
- src/components/RebalanceWidget/OrderImpact.tsx
- src/components/RouteLeavingPrompt.tsx
- src/components/SlideMenu/SideBarLink.tsx
- src/components/Tour/Tour.tsx
- src/styled/Group.ts
- src/styled/TwoFAManager.ts
- src/styled/global.tsx
> fix: change orange color

- src/selectors/groups.ts
> fixed target bar bug for cryptos

- src/selectors/groups.ts
> check for position currency value before parsing it

- src/components/Performance/SettingsComponents/Settings.tsx
> fix: styling for chart options on reporting page

- src/components/SlideMenu/SideBarLink.tsx
- src/styled/Rebalance.ts
> fix: make a space between group loading spinner and the name

- src/components/ModelPortfolio/SharedModelPortfolio.tsx
- src/components/SlideMenu/index.tsx
- remove *
- replace the text in the CTA box with the one Bly provided
> fix: on shared model page,  - collapse the sidebar by default

- src/selectors/performance.ts
- src/types/performance.ts
> change to improve caching behaviour with reporting settings

- package.json
- src/components/ModelAssetClass/index.tsx
- src/components/ModelAssetClass/tests/index.test.tsx
Opened this PR only to see the changes in codecov as we add more unit tests 
> my first unit test (asset classes page)

- src/components/Performance/AccountsSelect.tsx
- src/components/Performance/SettingsComponents/Settings.tsx
- src/types/performance.ts
> Removed include brokerage reporting settings

- src/components/ModelPortfolio/MoreOptions.tsx
- src/components/ModelPortfolio/index.tsx
> updated toast text

- src/components/PortfolioGroupTargets/index.tsx
> added a minor copy improvement

- src/components/Performance/Performance.tsx
- src/components/Performance/PerformanceRateOfReturn.tsx
> better handling of rate of return when = 0

- src/components/ModelPortfolio/SharedModelPortfolio.tsx
> fix: image size on shareable model page

- src/components/RebalanceWidget/OrderImpact.tsx
- src/components/RebalanceWidget/OrderImpacts.tsx
- src/components/RebalanceWidget/index.tsx
- src/components/TradesExplanation.tsx
- src/types/groupInfo.ts
> Show currency exchange rates
